language: node_js

sudo: false

cache:
    directories:
     - node_modules

node_js: stable

# install: 
	

scripts:
	- npm install -D
	- cd ./test/smoke/template
	- npm install -D
	- cd ../../../
	- npm test

